# fly.toml app configuration file generated for nest-farm on 2023-05-21T19:43:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nest-farm"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
